spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: MYR142578
    driver-class-name: com.mysql.cj.jdbc.Driver
  #session
  session:
    timeout: 86400


